### ISSUE TITLE
Installing Ecobee (Connect)-Error on Preferences Page

### ISSUE THREAD

**Issue by snakedog116** [StrykerSKS/SmartThings#6]
When installing the Ecobee (Connect) SmartApp I get the following on the final page (which is supposed to be where you specify some final settings:
It's a white page with 
"Other Preferences"
and then below that in grey it says:
"Lorum lpsum otherprefs"

**Comment by StrykerSKS** [comment]
I've switched over to the public repository so that I can do pull request back into the main code base. 

Use the one here instead: 
https://github.com/StrykerSKS/SmartThingsPublic/tree/StrykerSKS-Ecobee3/smartapps/smartthings/ecobee-connect.src

This is the one I have been focused on now. I guess I should delete the one in this repository in order to avoid confusion!

**Comment by snakedog116** [comment]
Ok, will do.

Can you enable 'issues' in your new fork?
